issue: API Unexpected Data Warnings
osTicket/osTicket pull request #4861
Opened 2019-04-22 18:32 UTC by JediKev

This addresses an issue reported on the Forum where `API Unexpected Data` warnings are appearing in the system logs for the `thread_entry_recipients` and `system_emails` keys for piped emails. This is due to the API request validator that checks the keys of the API data; if a key's data is an array itself it loops through the validator again to check the key(s) inside the data array. This is fine for most keys but for the `thread_entry_recipients` and `system_emails` keys the request structure does not contain the necessary sub-keys to validate the data keys. This adds the necessary sub-keys to the request structure so that `thread_entry_recipients` and `system_emails` data keys can be validated. This also adds a data key named "emails" to the setters for `system_emails` so they can be appropriately validated against the request structure.

2019-04-22 22:19 UTC, protich requested changes

2019-04-22 22:19 UTC, protich commented on include/class.mailparse.php
> +                    $data['system_emails']['emails'][] = $emailId;
I don't understand why you introduced `emails` key here  - it will absolutely break use of `system_emails` systemwide.

2019-05-09 18:51 UTC, merged

2020-02-12 07:42 UTC, Vudubond commented
Hello,

I have :

Server Information
--
osTicket Version | v1.12 (a076918) —  Up to date
Web Server Software | Apache
MySQL Version | 5.5.62
PHP Version | 7.1.33

I implemented https://github.com/osTicket/osTicket/commit/4f68eb9dbea010dbd98df09b9d78848d77509735

Because I had errors with :thread_entry_recipients and system_emails, 

API Unexpected Data
thread_entry_recipients: Unexpected data received in API request
 
API Unexpected Data
system_emails: Unexpected data received in API request

but now are getting:

API Unexpected Data
thread_entry_recipients/cc/1: Unexpected data received in API request

 API Unexpected Data
thread_entry_recipients/to/1: Unexpected data received in API request

2020-02-12 14:35 UTC, JediKev commented
@Vudubond

If I were you I’d upgrade to v1.12.5 or v1.14.1 and retest.

Cheers.