Task Inline Edit
osTicket/osTicket pull request #5223
Opened 2019-11-25 20:37 UTC by aydreeihn

Allow inline edit for the following on tasks:
- custom fields
- Status
- Department
- Due Date
- Assign

2020-02-04 20:38 UTC, JediKev commented on include/staff/templates/task-view.tmpl.php
> +                                        $v ?: '<span class="faded">&mdash;' . __('Empty') .  '&mdash; </span>');
`Format::strip_tags()`

2020-02-04 21:33 UTC, aydreeihn commented
@JediKev I have rebased and added the commit to ensure that we are able to clear long answer fields and edit them again. This is ready to be merged now.

2020-04-09 19:29 UTC, aydreeihn commented
@protich @JediKev I ended up putting the updateField function in the task and ticket class because Threadable is an interface and I couldn't create a new class that extended VerySimpleModel because I got the error 'Model does not define meta.table'.

2020-04-16 04:10 UTC, protich requested changes

2020-04-16 04:10 UTC, protich commented on include/class.orm.php
> +
drop this errant space / changes to this file.

2020-04-16 04:10 UTC, protich commented on include/ajax.tasks.php
> +                if (!$role->hasPerm(Ticket::PERM_CLOSE))
You mean `Task::PERM_CLOSE` ?

2020-04-16 04:13 UTC, protich commented
I'm also a little confused why you're using Ticket Statuses! Task doesn't have status_id -  it uses flag field to set open / closed bit.

2020-04-16 17:15 UTC, aydreeihn commented on include/ajax.tasks.php
>              switch ($info['status']) {
We need to make sure we don't clear $action here because we use it to get the correct verb for the success message.

2020-04-16 17:16 UTC, aydreeihn commented on include/class.task.php
> -    function getStatusId() {
I decided this wasn't a good way to do things, so I got rid of it altogether. Can't rely on the status names staying the same...

2020-04-16 17:17 UTC, aydreeihn commented on include/staff/templates/status-options.tmpl.php
> +        if (isset($actions[$status->getState()])
This will make sure we only show Open or Closed in the dropdown list for tasks since those are the only options you can switch to.

2020-04-16 17:33 UTC, aydreeihn commented
@protich Ok, did some cleaning up on this. Sorry about that.

2020-04-21 14:06 UTC, protich commented on include/class.task.php
> +        switch(is_string($status) ? $status : strtolower($status->getName())) {
do you need to revert this change?

2020-04-21 17:43 UTC, aydreeihn commented on include/class.task.php
> +        switch(is_string($status) ? $status : strtolower($status->getName())) {
Yes, reverted now.

2020-04-22 03:12 UTC, protich approved these changes

2020-04-22 03:13 UTC, merged