oauth2: Strict Matching
osTicket/osTicket pull request #6466
Opened 2023-02-13 16:37 UTC by JediKev

This is a rewrite of osTicket/osTicket-plugins#263 where it was attempting to implement Strict Matching. This fully implements Strict Matching and adds functionality to check for this when retrieving a token and when saving SMTP with Same As Remote Mailbox. This also adds a new disabled field to the General Settings to show what email will be used as well as a help tip that further explains Strict Matching.

2023-02-13 18:11 UTC, protich requested changes
Some comments on the initial review.

2023-02-13 18:11 UTC, protich commented on include/class.email.php
> +        $config = ($this instanceof SmtpAccount
Why not put this logic in `getConfig()` function?  

PS: We hadn't had an issue yet because getCredentials considered auth backend (i.e delegated to mailbox), but it makes sense to have it as part of getConfig.

2023-02-13 18:11 UTC, protich commented on include/class.email.php
> +        return $token->isMatch($this->getEmail()->getEmail(), $this->isStrict());
Token can be null. I would recommend.

```php
return ($token && $token->isMatch($this->getEmail()->getEmail(), $this->isStrict()))
```

2023-02-13 18:11 UTC, protich commented on include/class.email.php
> +        return $cred->getAccessToken($this->getConfigSignature());
Credential can be null here!

```php
return ($cred && $cred->getAccessToken($this->getConfigSignature())); 
```

2023-02-13 19:48 UTC, protich commented
To avoid requiring OAuth2 Plugin upgrade in tandem with the core release - I'm suggesting we tag the strict mode flag to the backend id as shown below, for now, until we release v1.18.x series.

```diff
diff --git a/include/class.email.php b/include/class.email.php
index bc4943c6..0a1adea4 100644
--- a/include/class.email.php
+++ b/include/class.email.php
@@ -522,7 +522,8 @@ class EmailAccount extends VerySimpleModel {
             $id = sprintf('%s:%d',
                 $this->getAuthBk(), $this->getId());
             if ($this->isOAuthAuth())
-                $id .= sprintf(':%d', $this->getAuthId());
+                $id .= sprintf(':%d:%b',
+                    $this->getAuthId(), $this->isStrict());
 
             $this->bkId = $id;
         }
```

Thoughts? I'm open for a discussions as to why it makes sense as temp fix.

2023-02-14 18:56 UTC, MarcBanyard commented on include/class.email.php
> +        return $token->isMatch($this->getEmail()->getEmail(), $this->isStrict());
Just tested this and it needs to as per the recommendation from Peter as the token can be null.

2023-02-14 18:56 UTC, MarcBanyard commented on include/class.email.php
> +        return $cred->getAccessToken($this->getConfigSignature());
Just tested this and it needs to as per the recommendation from Peter as the token can also be null.

2023-02-14 18:56 UTC, JediKev commented on include/class.email.php
> +        return $token->isMatch($this->getEmail()->getEmail(), $this->isStrict());
Yes update coming soon

2023-02-14 20:17 UTC, MarcBanyard commented
> To avoid requiring OAuth2 Plugin version upgrade in tandem with the core release - I'm suggesting we tag the strict mode flag to the backend id as shown below, for now, until we release v1.18.x series.
> 
> ```diff
> diff --git a/include/class.email.php b/include/class.email.php
> index bc4943c6..0a1adea4 100644
> --- a/include/class.email.php
> +++ b/include/class.email.php
> @@ -522,7 +522,8 @@ class EmailAccount extends VerySimpleModel {
>              $id = sprintf('%s:%d',
>                  $this->getAuthBk(), $this->getId());
>              if ($this->isOAuthAuth())
> -                $id .= sprintf(':%d', $this->getAuthId());
> +                $id .= sprintf(':%d:%b',
> +                    $this->getAuthId(), $this->isStrict());
>  
>              $this->bkId = $id;
>          }
> ```
> 
> Thoughts? I'm open for a discussions as to why it makes sense as temp fix.

Why wait till v1.18.x series, as the fix for OAuth2 is required for users now.

I agree moving the **Strict Email Matching** to the core is a good idea, so the above pull (now with the recommended fixes for a null token) resolves the issue along with the minor change required in [#265](https://github.com/osTicket/osTicket-plugins/pull/265) for the OAuth2 plugin fix the issue for everyone who uses Microsoft 365 with Shared Mailboxes.

The sooner this can be released to the public the better as it is very much needed since Microsoft forcefully disabled basic auth on all tenants.
Even if it comes out as v1.17.3 with a revised version of the plugin as per pull [#265](https://github.com/osTicket/osTicket-plugins/pull/265) so users can update and get working using OAuth2 and ensure they do not access shared mailboxes with a username and password as this breaches Microsoft's licencing terms.

2023-02-14 20:35 UTC, JediKev commented
@MarcBanyard 

You are misinterpreting what he was saying. He's saying in order to avoid us having to make a database patch and force a major upgrade (1.18.x) we can simply add a temporary fix for now to release v1.17.4 and new builds of plugins (with the fixes included) and then worry about a major release later on.

Cheers.

2023-02-15 09:52 UTC, MarcBanyard commented
@JediKev & @protich any idea when you plan on releasing this as a temporary fix so the community can start using it?

2023-03-07 18:48 UTC, protich approved these changes

2023-03-07 18:48 UTC, merged